version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: context-providers-template-database
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    container_name: context-providers-template-adminer
    restart: always
    ports:
      - 8008:8080

volumes:
  db:
